### ISSUE TITLE
Thread safety of RingBuffer

### ISSUE THREAD

**Issue by LnnrtS** [pichenettes/stmlib#9]
I have a question about the ring buffer implementation in stmlib.

As I understand it is expected to be thread-safe with a single producer and a single consumer (for example for comunicating between an ISR and application code). However from how I understand it there is no guarantee that a compiler will not reorder the access to the buffer content and the the access to the pointer indices. In particular, this could lead to a situation where an element is expected to be read (pointer indices have been changed) but it hasn't actually been written to the buffer so the receiver would read an old/invalid element if a context switch happened right in that moment.

The reason for that is that (how I understand it) `volatile` does not imply a memory fence and the safe way to handle it would be through `std::atomic`.

Please note that I am not saying this implementation does not work on arm. The compiler might very well emit working code. I am just wondering to what extend this is guaranteed.

Thanks for taking the time!

**Comment by pichenettes** [comment]
Yeah, probably not thread-safe on anything more sophisticated than a single-core MCU.

**Comment by LnnrtS** [comment]
Just for the sake of completeness: I was talking about single-core MCUs and instruction reordering happening by the compiler.
